#!/usr/bin/env node
// Sync the ts-rs generated bindings into the thin client's source tree.
//
// `crates/kindling-types/bindings/` is the single source of truth for the
// domain types (generated by `cargo test -p kindling-types --features ts-rs`).
// npm packaging only includes files under the package directory, so the thin
// client keeps a COMMITTED copy of those bindings inside its own `src/generated/`
// and imports its domain types from there. This script regenerates that copy.
//
// Usage:
//   node packages/kindling/scripts/sync-types.mjs
//
// CI (the `ts-generated-copy` gate in .github/workflows/rust.yml) re-runs the
// ts-rs generation, runs this script, then `git diff --exit-code` over both the
// bindings and the copied dir; drift fails the build.
//
// Idempotent: it mirrors the bindings tree, removing any stale files first.

import { cp, mkdir, rm, readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, '..');
const repoRoot = join(packageRoot, '..', '..');

const sourceDir = join(repoRoot, 'crates', 'kindling-types', 'bindings');
const destDir = join(packageRoot, 'src', 'generated');

// The canonical schema version file is also vendored into the package so the
// runtime schema-version check resolves in the published npm package (npm only
// includes files under the package dir). Kept in lock-step here, drift-gated in
// CI alongside the generated types.
const schemaSrc = join(repoRoot, 'schema', 'version.json');
const schemaDestDir = join(packageRoot, 'schema');

// Header prepended to the generated barrel so consumers know not to edit it.
const BARREL_HEADER = `// AUTO-GENERATED. Do not edit by hand.
// Run \`node packages/kindling/scripts/sync-types.mjs\` to regenerate from
// crates/kindling-types/bindings (the ts-rs output).
`;

async function listTsFiles(dir, base = dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listTsFiles(full, base)));
    } else if (entry.name.endsWith('.ts')) {
      files.push(relative(base, full));
    }
  }
  return files;
}

/** Rewrite extensionless relative `import`/`export ... from "./X"` to `"./X.js"`. */
async function addJsExtensions(dir) {
  const files = await listTsFiles(dir);
  for (const rel of files) {
    const full = join(dir, rel);
    const src = await readFile(full, 'utf8');
    const rewritten = src.replace(
      /(from\s+["'])(\.\.?\/[^"']+?)(["'])/g,
      (match, pre, spec, post) =>
        spec.endsWith('.js') ? match : `${pre}${spec}.js${post}`,
    );
    if (rewritten !== src) {
      await writeFile(full, rewritten, 'utf8');
    }
  }
}

async function main() {
  if (!existsSync(sourceDir)) {
    console.error(
      `error: bindings source missing: ${sourceDir}\n` +
        'Run `cargo test -p kindling-types --features ts-rs` first.',
    );
    process.exit(1);
  }

  // Replace the whole generated tree so deletions in the source propagate.
  await rm(destDir, { recursive: true, force: true });
  await mkdir(destDir, { recursive: true });
  await cp(sourceDir, destDir, { recursive: true });

  // ts-rs emits extensionless relative imports (`import ... from "./Foo"`),
  // which the package's Node16 module resolution rejects. Rewrite them to add
  // the `.js` extension so the copied tree type-checks. This is a deterministic
  // transform of the source bindings, so the copy stays drift-checkable.
  await addJsExtensions(destDir);

  // Emit a barrel (`index.ts`) re-exporting every generated type so the thin
  // client can `export type * from './generated/index.js'`. ts-rs emits no
  // barrel of its own.
  const files = (await listTsFiles(destDir)).sort();
  const exports = files
    .filter((f) => f !== 'index.ts')
    .map((f) => {
      // './serde_json/JsonValue.ts' -> './serde_json/JsonValue.js'
      const spec = './' + f.replace(/\\/g, '/').replace(/\.ts$/, '.js');
      return `export type * from '${spec}';`;
    });
  await writeFile(
    join(destDir, 'index.ts'),
    BARREL_HEADER + '\n' + exports.join('\n') + '\n',
    'utf8',
  );

  console.log(`synced ${files.length} binding file(s) -> ${relative(repoRoot, destDir)}`);

  // Vendor the canonical schema version file into the package.
  if (!existsSync(schemaSrc)) {
    console.error(`error: canonical schema missing: ${schemaSrc}`);
    process.exit(1);
  }
  await mkdir(schemaDestDir, { recursive: true });
  await cp(schemaSrc, join(schemaDestDir, 'version.json'));
  console.log(
    `synced schema/version.json -> ${relative(repoRoot, join(schemaDestDir, 'version.json'))}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
