//! Cross-implementation parity: the Rust provider and orchestrator must
//! produce byte-identical results to the TypeScript implementation for
//! identical queries against the same database.
//!
//! `ts-parity.db` and `ts-parity.json` are generated by
//! `tests/fixtures/generate-parity-fixtures.mjs` from the built TS packages
//! with `Date.now()` pinned; this test replays every case through the Rust
//! implementation with the same pinned clock and compares the JSON output.
//!
//! Retired after Phase 4 of the Rust port (PORT-005 validation note).

use std::path::PathBuf;

use kindling_provider::{retrieve_at, LocalFtsProvider, RetrievalProvider};
use kindling_store::{SqliteKindlingStore, StoreOptions};
use kindling_types::{ProviderSearchOptions, RetrieveOptions, Timestamp};
use serde_json::Value;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

fn load_fixture() -> (SqliteKindlingStore, Value) {
    let store = SqliteKindlingStore::open_with_options(
        &fixture_path("ts-parity.db"),
        &StoreOptions { readonly: true },
    )
    .expect("fixture database should open read-only");
    let json = std::fs::read_to_string(fixture_path("ts-parity.json"))
        .expect("fixture json should be readable");
    let fixture: Value = serde_json::from_str(&json).expect("fixture json should parse");
    (store, fixture)
}

#[test]
fn search_results_match_ts_provider() {
    let (store, fixture) = load_fixture();
    let now = fixture["now"].as_i64().expect("fixture now") as Timestamp;
    let provider = LocalFtsProvider::from_store(&store);

    for case in fixture["searchCases"].as_array().expect("searchCases") {
        let name = case["name"].as_str().unwrap_or("?");
        let options: ProviderSearchOptions =
            serde_json::from_value(case["options"].clone()).expect("case options should parse");

        let results = provider
            .search(&options, now)
            .unwrap_or_else(|err| panic!("search case {name:?} failed: {err}"));
        let actual = serde_json::to_value(&results).expect("results should serialize");

        assert_eq!(
            actual,
            case["expected"],
            "search case {name:?} diverged from the TS provider\nactual: {}\nexpected: {}",
            serde_json::to_string_pretty(&actual).unwrap(),
            serde_json::to_string_pretty(&case["expected"]).unwrap(),
        );
    }
}

#[test]
fn retrieve_results_match_ts_orchestrator() {
    let (store, fixture) = load_fixture();
    let now = fixture["now"].as_i64().expect("fixture now") as Timestamp;
    let provider = LocalFtsProvider::from_store(&store);

    for case in fixture["retrieveCases"].as_array().expect("retrieveCases") {
        let name = case["name"].as_str().unwrap_or("?");
        let options: RetrieveOptions =
            serde_json::from_value(case["options"].clone()).expect("case options should parse");

        let result = retrieve_at(&store, &provider, &options, now)
            .unwrap_or_else(|err| panic!("retrieve case {name:?} failed: {err}"));
        let actual = serde_json::to_value(&result).expect("result should serialize");

        assert_eq!(
            actual,
            case["expected"],
            "retrieve case {name:?} diverged from the TS orchestrator\nactual: {}\nexpected: {}",
            serde_json::to_string_pretty(&actual).unwrap(),
            serde_json::to_string_pretty(&case["expected"]).unwrap(),
        );
    }
}
