// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapsuleStatus } from "./CapsuleStatus";
import type { CapsuleType } from "./CapsuleType";
import type { ScopeIds } from "./ScopeIds";

/**
 * Input for creating a new capsule. Optional fields are auto-generated.
 */
export type CapsuleInput = { id?: string, type: CapsuleType, intent: string, status?: CapsuleStatus, openedAt?: number, closedAt?: number, scopeIds: ScopeIds, observationIds?: Array<string>, summaryId?: string, };
