// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapsuleStatus } from "./CapsuleStatus";
import type { CapsuleType } from "./CapsuleType";
import type { ScopeIds } from "./ScopeIds";

/**
 * Bounded unit of meaning grouping related observations.
 *
 * Mirrors `Capsule` in `packages/kindling-core/src/types/capsule.ts`.
 */
export type Capsule = { id: string, type: CapsuleType, intent: string, status: CapsuleStatus, openedAt: number, closedAt?: number, scopeIds: ScopeIds, observationIds: Array<string>, summaryId?: string, };
