// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Observation } from "./Observation";

/**
 * One page of observations in stable `(ts ASC, id ASC)` order.
 */
export type ListObservationsResult = { 
/**
 * The matching observations for this page.
 */
observations: Array<Observation>, 
/**
 * Present iff more rows remain — pass it back as `cursor` to fetch the next
 * page. **Absent means enumeration is complete** (the completeness signal a
 * consumer needs for an exact count / set-difference).
 */
nextCursor?: string, };
