// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationKind } from "./ObservationKind";
import type { ScopeIds } from "./ScopeIds";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Atomic, immutable record of an event captured during development.
 *
 * Mirrors `Observation` in `packages/kindling-core/src/types/observation.ts`.
 * The `redacted` flag is the only mutable field (via explicit redaction APIs).
 */
export type Observation = { id: string, kind: ObservationKind, content: string, 
/**
 * Source-specific metadata stored as a JSON object.
 */
provenance: { [key in string]?: JsonValue }, ts: number, scopeIds: ScopeIds, redacted: boolean, };
