// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationKind } from "./ObservationKind";
import type { ScopeIds } from "./ScopeIds";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Input for creating a new observation. Optional fields are auto-generated.
 */
export type ObservationInput = { id?: string, kind: ObservationKind, content: string, provenance?: { [key in string]?: JsonValue }, ts?: number, scopeIds: ScopeIds, redacted?: boolean, };
