// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinTargetType } from "./PinTargetType";
import type { ScopeIds } from "./ScopeIds";

/**
 * Pinned reference to an observation or summary.
 *
 * Mirrors `Pin` in `packages/kindling-core/src/types/pin.ts`.
 */
export type Pin = { id: string, targetType: PinTargetType, targetId: string, reason?: string, createdAt: number, expiresAt?: number, scopeIds: ScopeIds, };
