// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinTargetType } from "./PinTargetType";
import type { ScopeIds } from "./ScopeIds";

/**
 * Input for creating a new pin. Optional fields are auto-generated.
 */
export type PinInput = { id?: string, targetType: PinTargetType, targetId: string, reason?: string, createdAt?: number, expiresAt?: number, scopeIds: ScopeIds, };
