// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pin } from "./Pin";
import type { RetrievedEntity } from "./RetrievedEntity";

/**
 * Pin together with the observation or summary it points at.
 */
export type PinResult = { pin: Pin, target: RetrievedEntity, };
