// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeIds } from "./ScopeIds";

/**
 * Options for a retrieval request.
 */
export type RetrieveOptions = { query: string, scopeIds: ScopeIds, 
/**
 * Deprecated: token-budget assembly is a downstream-system responsibility.
 * Prefer `max_candidates` for bounded result sets.
 */
tokenBudget?: number, maxCandidates?: number, includeRedacted?: boolean, };
