// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateResult } from "./CandidateResult";
import type { PinResult } from "./PinResult";
import type { RetrieveProvenance } from "./RetrieveProvenance";
import type { Summary } from "./Summary";

/**
 * Complete retrieval result: pins, optional current summary, ranked candidates, provenance.
 */
export type RetrieveResult = { pins: Array<PinResult>, currentSummary?: Summary, candidates: Array<CandidateResult>, provenance: RetrieveProvenance, };
