// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeIds } from "./ScopeIds";

/**
 * Provenance for a retrieval result.
 */
export type RetrieveProvenance = { query: string, scopeIds: ScopeIds, totalCandidates: number, returnedCandidates: number, truncatedDueToTokenBudget: boolean, providerUsed: string, };
