// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope identifiers for multi-dimensional isolation.
 *
 * All fields are optional to support partial scoping. Mirrors `ScopeIds`
 * in `packages/kindling-core/src/types/common.ts`.
 */
export type ScopeIds = { sessionId?: string, repoId?: string, agentId?: string, userId?: string, taskId?: string, };
