// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a new summary. Optional fields are auto-generated.
 */
export type SummaryInput = { id?: string, capsuleId: string, content: string, confidence: number, createdAt?: number, evidenceRefs: Array<string>, };
