// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level description of a capsule's content (typically LLM-generated).
 *
 * Mirrors `Summary` in `packages/kindling-core/src/types/summary.ts`.
 */
export type Summary = { id: string, capsuleId: string, content: string, 
/**
 * Quality/confidence score in `[0.0, 1.0]`.
 */
confidence: number, createdAt: number, evidenceRefs: Array<string>, };
